### PR TITLE
Fixed US Mountain Standard Time causing tests to fail

### PR DESCRIPTION
**Pull request by BitSprocket**
Hi Kelly,

It's a bit of a hack but I implemented US Mountain Standard Time in System tests.  Feel free to rework it or reject it if you don't think it's the best way to fix the problem.

### CODE REVIEW

**Comment by kellyethridge** [comment]
Hi BitSprocket,

Thanks for the contribution. I'll merge it and see how it goes :)

**Comment by BitSprocket** [comment]
@kellyethridge - off topic but I'm very intrigued by your documentation/ci/cd strategy.  I'm about to embark on a very large project and I'm keen to learning best practices.  I've looked at your source and found your doc strings but your help files (and website) contain much more content than is in your source.  I see that you're including some other html also.  Would you be willing to give me a rundown on your build automation?  Clearly you've got a really great pipeline and I'd like to abscond with your ideas-lol!

**Comment by kellyethridge** [comment]
Well, I don't have much of a build system actually. It's pretty manual. After I compile the DLL I have an Inno Setup script that gathers everything and creates an install EXE. As for the documentation I have a custom build of [VBDOX](https://sourceforge.net/projects/vbdox/) on Source Forge that adds some missing features and formats things more to my liking.  I can zip up the source and executables if you like. The example code in the docs are HTML beautified versions of the text so it looks appropriate when viewing. I use the site [http://hilite.me](http://hilite.me/) with a little bit of modified CSS to get the borders I'm looking for.

So I wish I could give you an actual strategy when it comes to this project, unfortunately, I don't have one :)

**Comment by BitSprocket** [comment]
@kellyethridge I would very much like whatever you are willing to share.  I use [DocFx](https://dotnet.github.io/docfx/) for my C# projects but it doesn't build the .chm file - only a static website.  I need to ship a help file with my VBA/VB6 projects because my clients (US Navy & Marine Corps) don't always have internet access when they deploy.

I found a [Jenkins module](https://github.com/jenkinsci/visual-basic-6-plugin) that I want to use to [automate my builds](http://zbz5.net/automating-build-visual-basic-6-project) (I haven't implemented any of this yet).  

I do have a specific question though, in your ArrayList class, the Add method has as part of it's docstring ' @include "..\DocIncludes\ArrayList.AddRange.html"  Is that a separate hand crafted html file?  I found that included file in source and understand that you just jammed _something_ into hilite.me to get it beautified but my question is did you manually create _something_?

**Comment by kellyethridge** [comment]
Ah, the .chm file. I forgot about that. I use Microsofts HTML Help Workshop. VBDOX can generate the .hhp file that the workshop can use to generate the .chm file.

The external html files are indeed hand-crafted. They are the same format as VBDOX documentation would be, but without the comment apostrophe. The formatted example code is just regular source code I wrote then copied into the code beautifier and copied back out. So yes, it's a manual process lol. But I'm not in any kind of hurry. So you may have to look in a different direction for any kind of automation.

Well, I can't seem to attach a zip file to this. Is there an email you'd like me to send the VBDOX to? I've included both the source and executable. The executable is in the release sub-folder.

**Comment by BitSprocket** [comment]
Sure and thanks. You can send to bitsprocket@gmail.com

________________________________

**Comment by tannerhelland** [comment]
Hi guys.  Sorry to jump in, but I just wanted to recommend an alternate approach for automated VB6 builds.

@wqweto has put together a helpful guide on [how to use a (free) Azure Pipelines setup for CI with VB6 including GitHub integration](http://www.vbforums.com/showthread.php?880049-RESOLVED-WIP-How-to-setup-CI-with-Azure-Pipelines-for-VB6-projects-on-github-com).  He helped me get this up-and-running with a [large VB6 project](https://github.com/tannerhelland/PhotoDemon/pull/281), and it's worked very well.

It won't help with documentation, alas (the scourge of all VB6 work), but for CI it's the best solution I've seen.

**Pull request merged**
